# Определяем upstream (группу серверов) для нашего приложения.
# Здесь мы можем обратиться к контейнеру 'todo-list' по его имени и порту 8080.
upstream todo_list {
    server todo-list:8080;  # либо имя сервиса либо контейнера(сервис правильнеее)
}

server {
    # Слушаем 80 порт
    listen 80;
    server_name npepub.ru www.npepub.ru;

    # Настройки для сжатия (рекомендуется)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Проксируем все запросы к нашему upstream
        proxy_pass http://todo_list;

        # Важные заголовки для правильной работы приложения
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Если ваше приложение использует WebSockets, добавьте эти строки
        # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection "upgrade";
    }

    # Пример: если у приложения есть папка со статическими файлами,
    # можно настроить Nginx раздавать их напрямую, минуя приложение.
    # location /static/ {
    #     alias /путь/до/статики/;
    # }
}