# Определяем upstream (группу серверов) для нашего приложения.
# Здесь мы можем обратиться к контейнеру 'todo-list' по его имени и порту 8080.
upstream todo_list {
    server todo-list:8080;  # либо имя сервиса либо контейнера(сервис правильнеее)
}
upstream scanner {
    server scanner:7000;
}

server {
    listen 80;
    server_name npepub.ru www.npepub.ru;

    # Настройки для сжатия (рекомендуется)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Проксируем все запросы к нашему upstream
        proxy_pass http://todo_list;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /scan/ {
            proxy_pass http://scanner/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
}