services:
  scanner:
    image: ghcr.io/woody-rn/task-scanner:latest
    container_name: task-scanner-dev
    ports:
      - "7000:7000"
    restart: unless-stopped
    volumes:
      - ${HOST_SCAN_PATH:-./scan-data}:/data/scan
    networks:
      - check_task_network