services:
  scanner:
    build:
      context: ..
      dockerfile: ./task-scanner/Dockerfile
    image: task-scanner:local
    container_name: task-scanner-dev
    ports:
      - "7000:7000"
    restart: unless-stopped
    volumes:
      - ${HOST_SCAN_PATH}:/data/scan
    networks:
      - check_task_network