services:
  todo-list:
    image: ghcr.io/woody-rn/task-todo-list:latest
    container_name: task-todo-list-prod
    networks:
      - check_task_network
    restart: unless-stopped

  scanner:
    image: ghcr.io/woody-rn/task-scanner:latest
    container_name: task-scanner-prod
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${HOST_SCAN_PATH:-./scan-data}:/data/scan
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    networks:
      - check_task_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: task-nginx-proxy
    ports:
      - "80:80"   # Публикуем стандартный HTTP порт наружу
      # - "443:443" # Раскомментируйте, когда будете добавлять SSL
    volumes:
      # Монтируем наш конфигурационный файл внутрь контейнера
      - ./config/prod/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - todo-list
      - scanner
    networks:
      - check_task_network
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    container_name: task-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=ru_RU.UTF-8"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - check_task_network
    restart: unless-stopped

  liquibase:
    image: liquibase/liquibase:4.33-alpine
    container_name: task-liquibase
    environment:
      - LIQUIBASE_SEARCH_PATH=/liquibase/changelog
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - --url=jdbc:postgresql://postgres:5432/${DB_NAME}
      - --username=${DB_USERNAME}
      - --password=${DB_PASSWORD}
      - --changeLogFile=changelog-master.yaml
      - update
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    networks:
      - check_task_network
    restart: no

  minio:
    image: minio/minio:latest
    container_name: task-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - check_task_network
    restart: unless-stopped

networks:
  check_task_network:
    name: check_task_network
    driver: bridge

volumes:
  postgres_data:
    name: task_postgres_data
  postgres_lib:
    name: task_postgres_lib
  minio_data:
    name: task_minio_data
